### ISSUE TITLE
{Suggestion}

### ISSUE THREAD

**Issue by StockiesLad** [FeltMC/Felt-API#8]
If this isn't planned already, add the old forge loading screen back and "burrow" quilts loading screen.

**Comment by unix-supremacist** [comment]
okay firstly a few problems with this

first this is very out of scope of the felt api, however i don't think it's a bad idea

i would just use a fork/heavily inspired mod of better loading screen by shedaniel, and have it as a separate mod called felt loading screen, with api's for registering things to the loading screen baked into felt api, but no implementation

since @Trinsdar and i have to use mod menu i was thinking we could do the same thing for that too, with similar apis

another two mods id put up for this, is a REI clone, that doesnt need plugins for recipe support (already have how to do this to an extent in my head) and a better version of waila/top so we can have something thats both top and waila users can agree on

even if we did all of these as separate mods though, no time to do them right now kek, and thats problem 2

problem 3 is does anyone want to work on them

so they won't be a thing for awhile atleast

**Comment by StockiesLad** [comment]
fair enough!
